# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('openduty', '0010_auto__add_field_eventlog_user__add_field_eventlog_incident_key__add_fi'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='service_to_escalate_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_to_escalate_to_id', to='openduty.Service'),
        ),
        migrations.AddField(
            model_name='schedulepolicyrule',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='service',
            name='send_resolve_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hipchat_room_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hipchat_room_url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rocket_webhook_url',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='send_resolve_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='action',
            field=models.CharField(choices=[(b'acknowledge', b'acknowledge'), (b'unacknowledge', b'unacknowledge'), (b'resolve', b'resolve'), (b'silence_service', b'silence service'), (b'unsilence_service', b'unsilence service'), (b'silence_incident', b'silence incident'), (b'unsilence_incident', b'unsilence incident'), (b'forward', b'forward'), (b'log', b'log'), (b'notified', b'notified'), (b'notification_failed', b'notification failed'), (b'trigger', b'trigger')], default=b'log', max_length=100),
        ),
        migrations.AlterField(
            model_name='incident',
            name='service_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident', to='openduty.Service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
