# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 21:39
# The application previously depended on the syncdb command to create
# the database schema.  Some columns did not exist in migrations.
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto__chg_field_schedulednotification_incident'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedulednotification',
            options={'verbose_name': 'scheduled_notifications', 'verbose_name_plural': 'scheduled_notifications'},
        ),
        migrations.AlterModelOptions(
            name='usernotificationmethod',
            options={'verbose_name': 'user_notification_method', 'verbose_name_plural': 'user_notification_methods'},
        ),
        migrations.AlterField(
            model_name='schedulednotification',
            name=b'incident',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='openduty.Incident'),
        ),
        migrations.AlterModelTable(
            name='schedulednotification',
            table='openduty_schedulednotification',
        ),
        migrations.AlterModelTable(
            name='usernotificationmethod',
            table='openduty_usernotificationmethod',
        ),
    ]
